
services:
  r1:
    build: ./r1
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net10:
        ipv4_address: 10.0.10.4
      net11:
        ipv4_address: 10.0.11.4   
      net14:
        ipv4_address: 10.0.14.3
  r2:
    build: ./r2
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net11:
        ipv4_address: 10.0.11.3
      net12:
        ipv4_address: 10.0.12.4
  r3:
    build: ./r3
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net12:
        ipv4_address: 10.0.12.3
      net13:
        ipv4_address: 10.0.13.4   
      net15:
        ipv4_address: 10.0.15.4
  r4:
    build: ./r4
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net13:
        ipv4_address: 10.0.13.3
      net14:
        ipv4_address: 10.0.14.4   
  ha:
    build: ./ha
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true    
    networks:
      net10:
        ipv4_address: 10.0.10.3

  hb:
    build: ./hb
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true    
    networks:
      net15:
        ipv4_address: 10.0.15.3

networks:
  net10:
    ipam:
      driver: default
      config:
        - subnet: 10.0.10.0/24
  net11:
    ipam:
      driver: default
      config:
        - subnet: 10.0.11.0/24
  net12:
    ipam:
      driver: default
      config:
        - subnet: 10.0.12.0/24
  net13:
    ipam:
      driver: default
      config:
        - subnet: 10.0.13.0/24
  net14:
    ipam:
      driver: default
      config:
        - subnet: 10.0.14.0/24
  net15:
    ipam:
      driver: default
      config:
        - subnet: 10.0.15.0/24





